### ISSUE TITLE
Preproduction assets configuration

### ISSUE THREAD

**Issue by Senen** [AyuntamientoMadrid/agendas#253]
[2017-12-28T17:27:55.417423 #14342] DEBUG -- : [Rollbar] Reporting exception: No route matches [GET] "/assets/https:/fonts.googleapis.com/css"
F, [2017-12-28T17:27:55.415115 #14346] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/assets/https:/fonts.googleapis.com/css"):
  actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  rollbar (2.15.5) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.10) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.10) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.10) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.10) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.10) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activesupport (4.2.10) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.8) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.10) lib/rails/engine.rb:518:in `call'
  railties (4.2.10) lib/rails/application.rb:165:in `call'
  newrelic_rpm (3.13.2.302) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  unicorn (4.9.0) lib/unicorn/http_server.rb:580:in `process_client'
  unicorn (4.9.0) lib/unicorn/http_server.rb:674:in `worker_loop'
  unicorn (4.9.0) lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
  unicorn (4.9.0) lib/unicorn/http_server.rb:140:in `start'
  unicorn (4.9.0) bin/unicorn:126:in `<top (required)>'
  /aytomad/app/agendas/agendas/shared/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
  /aytomad/app/agendas/agendas/shared/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'

D, [2017-12-28T17:27:55.418574 #14346] DEBUG -- : [Rollbar] Reporting exception: No route matches [GET] "/assets/https:/fonts.googleapis.com/css"

**Comment by Senen** [comment]
Closed via #257
